### ISSUE TITLE
Server status not detected

### ISSUE THREAD

**Issue by cyrilpawelko** [MrChausson/BeamMP-Manager#1]
Since api [start](https://github.com/MrChausson/BeamMP-Manager/blob/main/src/routes/api/start/%2Bserver.ts) or [stop](https://github.com/MrChausson/BeamMP-Manager/blob/main/src/routes/api/stop/%2Bserver.ts) invoke systemctl with the --user option, I've installed beammp as a user unit.
It works correctly for stop, start and restart, but server status is always inactive because it does not use the --user option :
```
$ /usr/bin/systemctl is-active beammp
inactive
$ /usr/bin/systemctl --user is-active beammp
active
```

**Comment by MrChausson** [comment]
Hey @cyrilpawelko
First of all thanks for taking interest in the Project!!
As you probably have seen it is still very a work in progress and I have not even tested this part yet. But I plan on finishing the project (or at least the essentials of it) before mid june. So I will put it on my own beammp server so I can test it properly. For now I only tested on my development machine.

Anyway thanks for the feedback, I will keep this issue open so I can fix it when I get back into the project. Or if you wish to you can (I think, I'm not sure if I have configured the repo for this) create a pull request and I will accept it.

**Comment by MrChausson** [comment]
It has been fixed in the latest [commit](https://github.com/MrChausson/BeamMP-Manager/commit/5f754e46293e03c60ef1bb560281b8a35acf3dcf).
Again thanks for the feedback.
